### ISSUE TITLE
Atualizar readme

### ISSUE THREAD

**Issue by PedroMarianoAlmeida** [PedroMarianoAlmeida/desenvolvimento-web-oficial#5]
- Tirar aquele código padrão do Next e passar pra português
- Incluir o site oficial
- Colocar uma referência ao Issues para quem quiser ajudar
- Escrever o passo a passo pro código rodar (baixar, yarn, e nem dev se não me engano, só perguntar lá no grupo do WhatsApp)

**Comment by Lu4nScr1pt1ng** [comment]
Sendo feito por mim.

**Comment by PedroMarianoAlmeida** [comment]
Parabéns!
