### ISSUE TITLE
Descobrir como ler arquivos dinamicamente

### ISSUE THREAD

**Issue by PedroMarianoAlmeida** [PedroMarianoAlmeida/desenvolvimento-web-oficial#6]
Iremos precisar acessar a pasta ```public/desafios/[id do desafio]``` dentro do componente ```src/modules/desafios/index``` para poder ver os anexos dos desafios.

O Suco fez o seguinte esboço
```
fs.readdir('/public/desafio/1, function (erro, arrayArquicos) {
    if (err) {
        return console.log('deu erro com diretório ');
    } 
   ArrayArquivos.map(aqui é o callback que corresponde a cada elemento que vc pode transformar num array ou fazer oq quiser )
});
```

Mas esse fs parece que tem só no Node e não no Next, algo assim.

**Comment by AJohnsoon** [comment]
fs só pode ser usado no Node, porém li que da pra usar o [API Router do next]( https://medium.com/@boris.poehland.business/next-js-api-routes-how-to-read-files-from-directory-compatible-with-vercel-5fb5837694b9) pra fazer, ou utilizar o [Axios](https://axios-http.com/docs/intro)

**Comment by PedroMarianoAlmeida** [comment]
Acabou que já fizemos uma gambiarra (que dá um pouquinho mais de trabalho pro usuário). É como vai ficar por enquanto =D
